name: Deploy review-gator

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build site"
    env:
      SITE_PATH: "_site/"
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies

      - name: Build review-gator
        run: |
          virtualenv -p python3 --system-site-packages .venv
          source .venv/bin/activate
          pip install -e .

      - name: Build site
        run: |
          mkdir -p ${{ env.SITE_PATH }}
          GITHUB_TOKEN=${{ secrets.PAT }} review-gator \
            --config config.yaml
          mv ${{ env.SITE_PATH }}/reviews.html \
            ${{ env.SITE_PATH }}/index.html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.SITE_PATH }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: "Deploy site"
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
